### PR TITLE
New landing page

### PR DESCRIPTION
**Pull request by secondl1ght**
I have coded up the new landing page based on the Figma design. I know there are still some final touches and comments being worked out, but I thought I would get this initial draft completed and then we can still make any adjustments after feedback. I also still need to setup the carousel component for the tweets section, I was having a hard time finding one that is compatible with embedded tweets because most of them are made for images. If anyone has any suggestions on how we should implement this section please let me know.

Here are some screenshots of how the site looks like right, hope you like it:

image

image

image

image

image

image

image

image

image

Cheers!

### CODE REVIEW

**Comment by bumi** [comment]
niiice. great job! Can you look with @MoritzKa together on it?

**Comment by secondl1ght** [comment]
Yep I'll just wait for feedback and then make any changes we need, if anyone knows a good way to get the tweets carousel working they can share that as well.

**Comment by secondl1ght** [comment]
Yep I'll just wait for feedback and then make any changes we need, if anyone knows a good way to get the tweets carousel working they can share that as well.

**Comment by MoritzKa** [comment]
Figma designs are updated. No major changes expected. 
Maybe @dylancom or @escapedcat can give some advise on how to build a carousel for Tweets.

**Comment by bumi** [comment]
maybe let's ignore the carousel, I don't think that is needed right now and we can improve other things first?

**Comment by escapedcat** [comment]
> can give some advise on how to build a carousel for Tweets

Are those tweets manually selected or is any dynamic choice planned? 
If it's manual selection I assume any preferred react-carousel will do. Would need to look into it.
Shouldn't block this PR I think. Carousel can be an enhancement.

**Comment by secondl1ght** [comment]
> Figma designs are updated. No major changes expected. Maybe @dylancom or @escapedcat can give some advise on how to build a carousel for Tweets.

Ok I will check the Figma file for updates and then this should be ready to be merged after that.

> maybe let's ignore the carousel, I don't think that is needed right now and we can improve other things first?

> > can give some advise on how to build a carousel for Tweets
> 
> Are those tweets manually selected or is any dynamic choice planned? If it's manual selection I assume any preferred react-carousel will do. Would need to look into it. Shouldn't block this PR I think. Carousel can be an enhancement.
> 
> Edit: _Uhm... yeah, reload page before sending and check if bumi already wrote this :P_

The tweets are manual, I tried using some React carousel components but I couldn't find one that works properly because most of them are made for images. These embedded tweets are React components themselves that have some styling from Twitter that is hard to overwrite. I agree we can put in a separate issue to track this and someone can take it on if they are interested. But if everyone thinks the tweets look good enough the way they are then we can include them to be merged in this PR...

**Comment by secondl1ght** [comment]
Ok I have made the little changes from the Figma, I think this is ready to be deployed now!

**Comment by MoritzKa** [comment]
@Tiana01 can you also have a look?

**Comment by Tiana01** [comment]
where is the link @MoritzKa 

>

**Comment by escapedcat** [comment]
> where is the link @MoritzKa

I assume Moritz was referring to the screenshots above.  

@kiwiidb you think it's easy-_ish_ to have k8s deployments for these branches so people can check a real environment? Not sure if it's worth the effort at this point though.

**Comment by secondl1ght** [comment]
I tried deploying to Netlify but it is not working for some reason, somebody deployed it there before successfully but I dont remember who it was. If anyone knows can they comment here so I can ask them how they did it. Not too familiar with Remix but I deployed other React apps there before and they worked no problem.

**Comment by escapedcat** [comment]
> I tried deploying to Netlify but it is not working for some reason, somebody deployed it there before successfully but I dont remember who it was. If anyone knows can they comment here so I can ask them how they did it.

Sounds like there's documentation missing? If this is solved would be nice to write it down.

**Comment by secondl1ght** [comment]
The weird thing is that `npm run build` and `npm start` run fine locally but not when deployed on Netlify.

**Comment by escapedcat** [comment]
What errors do you get?   
Got a link to something?

**Comment by kiwiidb** [comment]
Currently, all pushes to `main` are auto-deployed both on the dev environment and on the live environment.
We could easily auto-deploy all pushes to any branch to the dev environment, if that would be helpful. Maybe it would be a bit too chaotic when 2 people are pushing at the same time to different branches, though?

**Comment by escapedcat** [comment]
> We could easily auto-deploy all pushes to any branch to the dev environment, if that would be helpful. Maybe it would be a bit too chaotic when 2 people are pushing at the same time to different branches, though?

Yeah, that would be chaos. Was thinking about each PR (or special tagged PR) gets its own env, i.e. https://pr-92.regtest.getalby.com. But no idea how much effort it is with the current setup. So  might not be worth it. 
And if Netlify works for (certain?) PRs that's already good. Maybe we need to improve the docs for that?

**Comment by kiwiidb** [comment]
Oh, ok. Seperate subdomains per PR would be a bit too complex for what we are doing here.
We could also have a workflow that you have to trigger manually, input the branch name, which then deploys the latest commit of that branch on the dev environment.

**Comment by escapedcat** [comment]
Good to know that option. No need to do it now I guess. First would be nice for me to understand how people (can) use Netlify.

**Comment by bumi** [comment]
re: netlify remix needs to be specially configured for the backend. It can run with netlify functions but this project is not setup for that. (I don't really know much remix though)

I think the website is not so critical we should merge it and just make sure we are fast in fixing potential issues that somebody finds when actually seeing the page. 

so @MoritzKa merge whenever you want and then we all review again on getalby.com (it takes some minutes until it is deployed)

**Comment by secondl1ght** [comment]
Ok I am going ahead and merging this and me and @MoritzKa will jump on any hot fixes needed right away.

> Currently, all pushes to `main` are auto-deployed both on the dev environment (https://site.regtest.getalby.com) and on the live environment. We could easily auto-deploy all pushes to any branch to the dev environment, if that would be helpful. Maybe it would be a bit too chaotic when 2 people are pushing at the same time to different branches, though?

@kiwiidb I actually think if this is easy to setup maybe we should do this, this repo is not super active with new branches all the time and when someone pushes a new branch they could share the testing link right away to get feedback.. I mean it is better than people like @Tiana01 not being able to preview the work right?

**Pull request merged**
