### PR TITLE
update substack subscribe blog to ghost

### PR DESCRIPTION
**Pull request by secondl1ght**
@pooniajay noticed in #124 that we still have the Substack newsletter subscription widget on the landing page even though we have migrated to Ghost and the other links point to Ghost. I didn't see that Ghost has a similar embed widget as Substack (but if someone finds one let me know) so I re-created a similar style widget myself with a Subscribe button that takes you to the sub page on the Ghost blog.

image

### CODE REVIEW

**Comment by MoritzKa** [comment]
can we have a subscribe field so that visitors can enter their email directly?
We would also need to check what other information we need to show from a legal point of view.

**Comment by bumi** [comment]
Is ghost used to send also newsletters (and not only host the blog)? is this decision final?

**Comment by MoritzKa** [comment]
no, not final. 
Substack was built for newsletters and is very easy to handle in this regard.  
However, I am not a fan of the Substack email registration form. 
Can someone compare both solutions?

**Review by escapedcat — APPROVED** [review]

**Comment by bumi** [comment]
don't change that if you're not sure if you want to use ghost or substack for newsletters. => first be sure about that.

**Comment by pooniajay** [comment]
> Is ghost used to send also newsletters (and not only host the blog)? is this decision final?

Yes we have migrated entirely to Ghost. Substack is not needed anymore. The most recent newsletter went out via ghost

**Comment by bumi** [comment]
do you make sure that people who signup today on getalby.com (=> end up in substack) will also get the newsletter and will be imported to ghost? 

this needs to be fixed fast. @pooniajay do you own this? 
This issue is more than a week old, and you say ghost is used now already but obviously people still signup to substack and it seems nobody cares about that we get a proper signup form on our website?

**Comment by secondl1ght** [comment]
I know it is hard to believe that they don't have a simple pre-made iframe widget like Substack or an easy to use API, but I have looked over their documentation, help center, website etc. and not found any information about it. I am emailing their support right now and I am sure they will point me in the right direction, hopefully quickly. Then I can add the input form to the website.

If we want to get this out the door ASAP we could merge this one for now and then add the input form later. Regarding how the migration of Substack members works I am not sure, but I think whoever setup this blog should know about that.

**Comment by pooniajay** [comment]
@bumi i have access to substack subscribers too. If we get any in the interim will transfer them to ghost. I did the earlier migration too

**Comment by bumi** [comment]
This is not an option. This is useless manual, error prone work. 
The question is: how do we get this fixed? And who is owning this task that we get the blog running, integrated in the website and have a subscriber list. 

For example I also still find super confusing that there is a "sign up" form on the blog behind a main call to action - which is not a signup to Alby. etc. 
Who makes sure we get a good solution online?
image

**Comment by secondl1ght** [comment]
As far as the widget/API goes I am waiting to hear back from Ghost support. For updating other things about the blog, maybe we should make a list of changes we would like to see changed? I think many of them can be made inside the Ghost interface, the only one that was quite a bit of extra effort was making the headers/footers match exactly to the rest of the website. Things like changing 'Sign up' to 'Subscribe to newsletter' should be easy to change I think. I haven't spent much time on the Ghost blog interface but if we have a list of updates we want to make I could go through and see what can be done.

**Comment by MoritzKa** [comment]
what needs to be changed is part of the issues such as unifying header and footer. https://github.com/getAlby/website/issues/128 
What is the current status there? You already invested some time according to the time tracking.

**Comment by secondl1ght** [comment]
> what needs to be changed is part of the issues such as unifying header and footer. #128 What is the current status there? You already invested some time according to the time tracking.

I have Ghost running locally, forked a custom template, and created a new repo for us to track our Alby blog template. I have started working on unifying the headers and footers, I should be able to get this done this week no problem. 

Regarding this PR, I contacted Ghost support and found out some more information about adding a widget to external sites, I will also give this one a try this week and should be able to finish this PR off. I am meeting with @bumi today to discuss more, I think the blog will be totally finished and ready by the end of this week for sure. So we are getting close.

**Comment by pooniajay** [comment]
Pertaining to our discussion yesterday-
image

- [ ] There is a double check-in for a sign up, when you click on subscribe button on the blog. 

- [ ] 2. Tags have been assigned to all posts.

- [ ] 3. Ghost 5.0 has been updated

**Comment by MoritzKa** [comment]
Does the text in the message make sense? What should users be automatically signed in? 
Is this the e-mail that goes out to new subscribers for a double opt-in?

**Comment by bumi** [comment]
Does that mean that double-opt-in email IS actually required?

If so:
I would like to avoid "signup" for the newsletter. 
People do not signup for Alby. the email sounds like they get an Alby account, which they don't. They only confirm they want the email newsletter?

**Comment by pooniajay** [comment]
Right now the message says "Tap the link below to complete the signup process for Alby", I will change the text to "Tap the link below to complete the signup process for Alby Buzz"
This should establish the distinction that Alby Buzz is the newsletter. Is that okay? It can also be supported with the text in the proposed subscription button  design in [this issue](https://github.com/getAlby/website/issues/137) "Subscribe to the Alby Buzz" instead of "Subscribe to newsletter"

**Comment by bumi** [comment]
if you read that email would you understand what happens there? what do you signup for? what can you do when you signin? etc.?

**Comment by pooniajay** [comment]
> I would not know what "Alby Buzz" is. People would first need to learn what buzz is and understand that it means the newsletter.
> 
> As said I personally believe the word signup should not be used.

It isn't possible to customize from the Ghost theme settings but I think the [Ghost forum email customization thread here](https://forum.ghost.org/t/email-template-customization/9745/14) has some answers. 
We can replace "sign up" to "subscribe" everywhere. 

_Complete your subscription to Alby Buzz!
Hey there!

Tap the link below to complete the subscription process for Alby Buzz, and be automatically signed in:
Confirm subscription

For your security, the link will expire in 24 hours time.
See you soon!_

Is this resolution okay?

**Comment by pooniajay** [comment]
For @secondl1ght 's comment i'll request @MoritzKa 's opinion/resolution suggestion

**Comment by pooniajay** [comment]
1. 
_Complete your subscription to Alby Buzz!
Hey there!

Tap the link below to complete the subscription process for Alby Buzz, and be automatically subscribed:
Confirm subscription

For your security, the link will expire in 24 hours time.
See you soon!_

And 2.
In #138 we can replace - 
Subscribe to newsletter -> Subscribe to the Alby Buzz
You're signed up -> You're subscribed

**Comment by MoritzKa** [comment]
Double opt-in is not required by GDPR. Should we actually ask the user for a double confirmation per email ([Source](https://www.iubenda.com/en/help/22127-gdpr-double-opt-in#:~:text=What's%20double%20opt%2Din%3F,added%20to%20your%20mailing%20list.))? 
Personally I would not require that. What do you say @bumi ? 
Sorry for causing confusion.

**Comment by secondl1ght** [comment]
Closed in favor of #138 

(discussion can continue here though)

**Comment by bumi** [comment]
I was wondering what the ghost/etc. requirements are. 
I leave that up to you. 

Regarding copy: if you think that's good, I am fine! think as a visitor/user and how they will interact with Alby.


https://blog.emailoctopus.com/single-vs-double-opt-in-which-is-best/

**Comment by pooniajay** [comment]
Hi @secondl1ght , we'll have to change the copy in the email subscription link to what I have [mentioned above](https://github.com/getAlby/website/pull/135#issuecomment-1150560060). 
image

**Pull request closed without merging**
