### PR TITLE
Fix/improve lighthouse stats

### LINKED ISSUE #110: Improve Lighthouse stats
Report :
[GETALBY_LIGHTHOUSE_REPORT.pdf](https://github.com/getAlby/website/files/8309309/GETALBY_LIGHTHOUSE_REPORT.pdf)

These were the network stats for hard reload:
image

Typical reload with caching:
image

Even in a typical reload, the time to get the site interactive is much higher, and there are huge layout shifts. It's mainly because of a few huge files, in particular, 1 file with a size of 8.5MB ( It alone takes around 1.2 min to load, making the user experience worse )
image

### PR DESCRIPTION
**Pull request by RajVarsani**
Changes
- Added images in PNG and WEBP formats
- Updated site images from SVG to WEBP

### Updated Report: [GETALBY_LIGHTHOUSE_REPORT_UPDATED.pdf](https://github.com/getAlby/website/files/8373577/GETALBY_LIGHTHOUSE_REPORT_UPDATED.pdf)

Test deploy: https://test-deploy.centralindia.cloudapp.azure.com/

VM configs: 
> Platform: Azure
> Operating system: Linux (ubuntu 18.04)
> Size: Standard B1ls (1 vcpu, 0.5 GiB memory)
> Location : Central India
>
> Disk | Type | Size (GiB) | Max IOPS | Max throughput (MBps) 
> --- | --- | --- | --- | ---
> OS Disk | Premium SSD LRS | 30 | 120 | 25 
> Data Disk | Premium SSD LRS | 4 | 120 | 25 

SEO still has some scope for improvement. I'll go through that and update it here.

resolves #110

### CODE REVIEW

**Comment by bumi** [comment]
super cool. 
how good is the webp support? (I am old :)) I think Safari does not support that well, does it? 

(just to confirm: for png files you also have removed the meta data to make it smaller? (like something that https://tinypng.com/ and others do))

**Comment by RajVarsani** [comment]
Safari supports WEBP since V14 ig.

**Comment by RajVarsani** [comment]
image
Except for Internet Explorer and KaiOS Browser, all browsers seem to support it.

**Comment by RajVarsani** [comment]
Regarding PNGs, I haven't optimized those as WEBPs were used on the site.

**Comment by bumi** [comment]
there are some pngs in the PR, no? 

for Safari it says it only supports Big Sur or later and also mobile versions are only rather recent. 
I think a website should work on as much devices as possible, also old ones. (we actually have macOS users with old versions) can we have a fallback for those? or otherwise I'd rather use png - what is the big webp advantage?

image

**Comment by bumi** [comment]
@RajVarsani I merge this. but what do you think about my comment above?

**Comment by RajVarsani** [comment]
Sorry, got a bit inactive because of studies stuff.

The major benefit of using WEBP over PNG is size only. Ig it has somewhat 25-30% lesser size for the same quality.
And regarding the versions, Safari V14 is in macOS Mojave, too, So we'll be on the safe side, I suppose.

image
image

**Pull request merged**
