### PR TITLE
Update styling for Home page

### LINKED ISSUE #75: Update styling for home page
On the current site, content gets farther away for larger screens, making UI a bit uncomfortable and confusing for users.

image

It can be changed to something similar to this.

image

### PR DESCRIPTION
**Pull request by RajVarsani**
resolves #75

### CODE REVIEW

**Comment by secondl1ght** [comment]
@bumi do you want me to review this?

**Comment by bumi** [comment]
@secondl1ght no need to ask. Any PR in any repo everywhere can and should be reviewed. If you have input, then comment on it.

**Comment by RajVarsani** [comment]
As mentioned by @Tiana01, I've tested aligning content and banner with logo and buttons, respectively. 
Problems I've encountered : 
- Shadow in banner image causes negative space at the right and bottom side of the image.
  image
  - A pretty straightforward solution to this would be to cast shadows manually with CSS. ( In the screenshot below, For just testing purposes, I've handled it with transform ).
  image
- Seems working, but with this layout in smaller screens (e.g., 14 / 12 Inches ), a shadow at the end was creating a bit dark at the right end of the viewport; not sure if you can get a clear idea from ss below. You may try it at your locale and see it.
   image

Please update if someone has some solution or suggestion to this.

So, I've only pushed the banner change from png to SVG for now. The quality difference of using is the SVG is clearly visible. The downside of this is that it requires approximately +20KB of bandwidth (SVG  -> 308KB & png -> 288KB). I've also pushed webp format for the banner that is even less than 100KB, which we can use instead of PNG if we decide not to go with SVG.

**Review by secondl1ght — CHANGES_REQUESTED** [review]
Thanks for the PR! Sorry it took so long to get this reviewed. I have it running locally, have you checked the mobile view after making these changes? It looks like the mobile responsiveness is broken, can you make some more updates to fix this?
Here's a screenshot of what I see on my end:
image

**Comment by RajVarsani** [comment]
Sorry, I forgot to check for mobile devices. Let me see what I can do.

**Comment by RajVarsani** [comment]
There was an issue with the max-width of the banner image. All other params deciding its width were at auto value, so I think its width was calculated the same as its max-width.

**Review by secondl1ght — APPROVED** [review]

**Comment by secondl1ght** [comment]
Awesome looks like the mobile view is fixed now!

LGTM @bumi

**Pull request merged**
